site_name: Jake Lindsay's Blog
theme: 
  logo: imgs/favicon.ico
  favicon: imgs/favicon.ico
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.instant.prefetch
  highlightjs: true
  user_color_mode_toggle: true
site_author: Jake Lindsay <jake@jakelindsay.uk>
site_description: Jake Lindsay's blog.
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - index.md
  - Blog:
    - blog/index.md
plugins:
    - blog
    - search
extra_javascript:
    - javascripts/oneko.js